COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:minimal-json',
    '//protocols/p4runtime/model:onos-protocols-p4runtime-model',
    '//drivers/default:onos-drivers-default',
    '//protocols/p4runtime/api:onos-protocols-p4runtime-api',
]

osgi_jar (
    deps = COMPILE_DEPS,
)

BUNDLES = [
    '//apps/intP4/pipeconf:onos-apps-intP4-pipeconf',
]

onos_app (
    app_name = 'org.onosproject.intP4.pipeconf',
    title = 'INT P4 Pipeconf',
    category = 'Pipeconf',
    url = 'http://onosproject.org',
    description = 'Provides pipeconf for the ONOS-P4 In-Band Network Telemetry App',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.drivers.p4runtime',
    ]
)
